openapi: 3.0.3
info:
  title: Housing Price Analysis API
  description: |
    不動産価格分析ダッシュボード用API

    国土交通省の不動産取引価格情報に基づく実際の取引データを提供します。
    データ形式は国土交通省のオープンデータ仕様に準拠しています。

    主な物件タイプ:
    - 中古マンション等
    - 宅地(土地と建物)
    - 宅地(土地)

    取引データには価格、面積、建築年、構造、都市計画情報等が含まれます。
  version: 1.0.0
  contact:
    name: Housing Price Analysis Team
    email: support@housing-price.com

servers:
  - url: http://localhost:8000/api
    description: Development server
  - url: https://api.housing-price.com
    description: Production server

paths:
  /areas/search:
    get:
      tags:
        - Areas
      summary: 条件に基づいて比較エリアを検索
      description: 物件タイプ、構造、間取り、地域などの条件に基づいて比較可能なエリアを検索
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AreaSearchRequest"
            example:
              propertyTypes: ["中古マンション等"]
              structures: ["wood"]
              layouts: ["2K", "2DK"]
              prefecture: "tokyo"
              city: "setagaya"
              districtName: "shibuya"
              durationInYears: 3
      responses:
        "200":
          description: 検索結果の比較エリア情報
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AreaSearchResponse"
              example:
                areas:
                  - prefecture: "東京都"
                    city: "港区"
                    districtName: "新橋"
                    tradePrice: "180000000"
                    area: "65"
                    buildingYear: "2002年"
                    structure: "ＲＣ"
                    cityPlanning: "商業地域"
                    coverageRatio: "80"
                    floorAreaRatio: "600"
                    period: "2025年第1四半期"
                    renovation: "未改装"

  /locations/municipalities:
    get:
      tags:
        - Locations
      summary: 市区町村一覧を取得
      description: 指定された都道府県の市区町村一覧を取得
      parameters:
        - name: prefecture
          in: query
          required: true
          description: 都道府県名
          schema:
            type: string
            example: "東京都"
      responses:
        "200":
          description: 市区町村一覧
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MunicipalitiesResponse"
              example:
                cities:
                  - code: "chiyoda"
                    name: "千代田区"
                  - code: "chuo"
                    name: "中央区"
                  - code: "minato"
                    name: "港区"
                  - code: "shinjuku"
                    name: "新宿区"
                  - code: "setagaya"
                    name: "世田谷区"
        "400":
          description: パラメータが不正
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /locations/districts:
    get:
      tags:
        - Locations
      summary: 地区名一覧を取得
      description: 指定された市区町村の地区名（町名等）一覧を取得
      parameters:
        - name: prefecture
          in: query
          required: true
          description: 都道府県名
          schema:
            type: string
            example: "東京都"
        - name: municipality
          in: query
          required: true
          description: 市区町村名
          schema:
            type: string
            example: "港区"
      responses:
        "200":
          description: 地区名一覧
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DistrictsResponse"
              example:
                districts:
                  - code: "akasaka"
                    name: "赤坂"
                  - code: "azabu"
                    name: "麻布"
                  - code: "higashishinbashi"
                    name: "東新橋"
                  - code: "nippori"
                    name: "虎ノ門"
                  - code: "roppongi"
                    name: "六本木"
        "400":
          description: パラメータが不正
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    AreaSearchRequest:
      type: object
      required:
        - propertyTypes
        - durationInYears
      properties:
        propertyTypes:
          type: array
          items:
            type: string
            enum: ["中古マンション等", "宅地(土地と建物)", "宅地(土地)"]
          description: 物件タイプ（複数選択可）
        propertyStatuses:
          type: array
          items:
            type: string
            enum: ["new", "used"]
          description: 物件状態（複数選択可）
        structures:
          type: array
          items:
            type: string
            enum: ["wood", "RC", "SRC"]
          description: 構造（複数選択可）
        layouts:
          type: array
          items:
            type: string
            enum: ["1R_1K", "1DK", "2K", "2DK", "3LDK", "4LDK_plus"]
          description: 間取り（複数選択可）
        prefecture:
          type: string
          description: 都道府県コード
        city:
          type: string
          description: 市区町村コード
        station:
          type: string
          description: 最寄り駅・地区コード
        durationInYears:
          type: integer
          enum: [1, 3, 5, 10]
          description: 分析期間（年数）

    AreaSearchResponse:
      type: object
      properties:
        areas:
          type: array
          items:
            $ref: "#/components/schemas/AreaInfo"

    AreaInfo:
      type: object
      properties:
        id:
          type: string
          description: エリアID
        name:
          type: string
          description: エリア名
        districtName:
          type: string
          description: 地区名
        prefecture:
          type: string
          description: 都道府県コード
        city:
          type: string
          description: 市区町村コード
        station:
          type: string
          description: 最寄り駅・地区コード
        coordinates:
          $ref: "#/components/schemas/Coordinates"
        marketInfo:
          $ref: "#/components/schemas/MarketInfo"

    Coordinates:
      type: object
      properties:
        latitude:
          type: number
          format: float
          description: 緯度
        longitude:
          type: number
          format: float
          description: 経度

    MarketInfo:
      type: object
      properties:
        averagePrice:
          type: number
          description: 平均価格（万円）
        averageUnitPrice:
          type: number
          description: 平均単価（万円/㎡）
        transactionCount:
          type: integer
          description: 取引件数

    PriceDataResponse:
      type: object
      properties:
        areaId:
          type: string
          description: エリアID
        areaName:
          type: string
          description: エリア名
        duration:
          type: integer
          description: 取得期間（年数）
        chartLabels:
          type: array
          items:
            type: string
          description: チャートのラベル配列
        priceData:
          type: array
          items:
            type: number
          description: 価格データ配列（万円）
        unitPriceData:
          type: array
          items:
            type: number
          description: 単価データ配列（万円/㎡）

    TransactionSearchRequest:
      type: object
      required:
        - areaIds
      properties:
        areaIds:
          type: array
          items:
            type: string
          description: 検索対象エリアID配列
        propertyTypes:
          type: array
          items:
            type: string
            enum: ["中古マンション等", "宅地(土地と建物)", "宅地(土地)"]
          description: 物件タイプフィルタ
        structures:
          type: array
          items:
            type: string
            enum: ["wood", "RC", "SRC"]
          description: 構造フィルタ
        layouts:
          type: array
          items:
            type: string
          description: 間取りフィルタ
        limit:
          type: integer
          default: 50
          description: 取得件数上限
        offset:
          type: integer
          default: 0
          description: 取得開始位置

    TransactionHistoryResponse:
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: "#/components/schemas/TransactionRecord"
        totalCount:
          type: integer
          description: 総取引件数
        hasMore:
          type: boolean
          description: さらに取引データがあるかどうか

    TransactionRecord:
      type: object
      required:
        - Type
        - Prefecture
        - Municipality
        - TradePrice
        - Period
      properties:
        Type:
          type: string
          enum: ["中古マンション等", "宅地(土地と建物)", "宅地(土地)"]
          description: 取引物件の種類
          example: "中古マンション等"
        Prefecture:
          type: string
          description: 都道府県名
          example: "東京都"
        Municipality:
          type: string
          description: 市区町村名
          example: "港区"
        DistrictName:
          type: string
          description: 地区名（町名等）
          example: "東新橋"
        TradePrice:
          type: string
          description: 取引価格（円、文字列形式）
          example: "180000000"
        Area:
          type: string
          description: 面積（㎡、文字列形式）
          example: "65"
        BuildingYear:
          type: string
          description: 建築年
          example: "2002年"
        Structure:
          type: string
          description: 建物の構造
          example: "ＲＣ"
        CityPlanning:
          type: string
          description: 都市計画区域
          example: "商業地域"
        CoverageRatio:
          type: string
          description: 建ぺい率（%、文字列形式）
          example: "80"
        FloorAreaRatio:
          type: string
          description: 容積率（%、文字列形式）
          example: "600"
        Period:
          type: string
          description: 取引時期（四半期表示）
          example: "2025年第1四半期"
        Renovation:
          type: string
          description: リフォーム・リノベーション状況
          example: ""

    PrefecturesResponse:
      type: object
      properties:
        prefectures:
          type: array
          items:
            $ref: "#/components/schemas/Prefecture"

    Prefecture:
      type: object
      properties:
        code:
          type: string
          description: 都道府県コード
        name:
          type: string
          description: 都道府県名
        cities:
          type: array
          items:
            $ref: "#/components/schemas/City"

    City:
      type: object
      properties:
        code:
          type: string
          description: 市区町村コード
        name:
          type: string
          description: 市区町村名

    StationsResponse:
      type: object
      properties:
        stations:
          type: array
          items:
            $ref: "#/components/schemas/Station"

    Station:
      type: object
      properties:
        code:
          type: string
          description: 駅・地区コード
        name:
          type: string
          description: 駅・地区名
        stationType:
          type: string
          enum: ["station", "district"]
          description: タイプ（駅または地区）

    MunicipalitiesResponse:
      type: object
      properties:
        municipalities:
          type: array
          items:
            $ref: "#/components/schemas/Municipality"

    Municipality:
      type: object
      properties:
        code:
          type: string
          description: 市区町村コード
        name:
          type: string
          description: 市区町村名

    DistrictsResponse:
      type: object
      properties:
        districts:
          type: array
          items:
            $ref: "#/components/schemas/District"

    District:
      type: object
      properties:
        code:
          type: string
          description: 地区コード
        name:
          type: string
          description: 地区名

    MarketSummaryResponse:
      type: object
      properties:
        totalAreas:
          type: integer
          description: 総エリア数
        totalTransactions:
          type: integer
          description: 総取引件数
        averagePrice:
          type: number
          description: 全体平均価格（万円）
        averageUnitPrice:
          type: number
          description: 全体平均単価（万円/㎡）
        priceChangeRate:
          type: number
          description: 価格変動率（%）
        lastUpdated:
          type: string
          format: date-time
          description: 最終更新日時

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: エラーメッセージ
        code:
          type: string
          description: エラーコード
        details:
          type: object
          description: エラー詳細情報

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []

tags:
  - name: Areas
    description: エリア検索・管理
  - name: Locations
    description: 地域情報
